---
version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/local"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    reviewers:
      - "elastic/observablt-ci"

  # Enable version updates for pytest_otel
  - package-ecosystem: "pip"
    directory: "resources/scripts/pytest_otel"
    # Check for updates once a month
    schedule:
      interval: "weekly"
    reviewers:
      - "elastic/observablt-ci"
      - "kuisathaverat"
