---
version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: "maven"
    # Look for `pom.xml` file in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "monthly"
    reviewers:
      - "elastic/observablt-ci"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/local"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    reviewers:
      - "elastic/observablt-ci"

  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directory: ".ci/jobDSL"
    # Check for updates once a week
    schedule:
      interval: "monthly"
    reviewers:
      - "elastic/observablt-ci"
