---
version: 2
updates:
  # Enable version updates for pytest_otel
  - package-ecosystem: "pip"
    directory: "resources/scripts/pytest_otel"
    # Check for updates once a month
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "elastic/observablt-ci"
      - "kuisathaverat"

  # Maintain dependencies for GitHub Actions (/.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "elastic/observablt-ci"
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"

  # Maintain dependencies for GitHub composite Actions (/.github/actions)
  # Waiting for supporting wildcards, see https://github.com/dependabot/dependabot-core/issues/5137
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "elastic/observablt-ci"
    labels:
      - dependencies
    directories:
      - "/.github/actions/await-maven-artifact"
      - "/.github/actions/buildkite"
      - "/.github/actions/check-dependent-jobs"
      - "/.github/actions/comment-reaction"
      - "/.github/actions/deploy-my-kibana"
      - "/.github/actions/docker-layer-caching"
      - "/.github/actions/docker-login"
      - "/.github/actions/elastic-stack-snapshot-branches"
      - "/.github/actions/github-token"
      - "/.github/actions/is-admin"
      - "/.github/actions/is-member-elastic-org"
      - "/.github/actions/is-pr-author-member-elastic-org"
      - "/.github/actions/kibana-docker-image"
      - "/.github/actions/notify-build-status"
      - "/.github/actions/oblt-cli"
      - "/.github/actions/oblt-cli-cluster-credentials"
      - "/.github/actions/oblt-cli-cluster-name-validation"
      - "/.github/actions/oblt-cli-create-ccs"
      - "/.github/actions/oblt-cli-create-custom"
      - "/.github/actions/oblt-cli-create-serverless"
      - "/.github/actions/oblt-cli-destroy-cluster"
      - "/.github/actions/opentelemetry"
      - "/.github/actions/pre-commit"
      - "/.github/actions/publish-report"
      - "/.github/actions/setup-git"
      - "/.github/actions/setup-npmrc"
      - "/.github/actions/setup-oblt-cli"
      - "/.github/actions/setup-vault-cli"
      - "/.github/actions/slack-message"
      - "/.github/actions/snapshoty"
      - "/.github/actions/snapshoty-simple"
      - "/.github/actions/test-report"
      - "/.github/actions/updatecli"
      - "/.github/actions/validate-github-comment"
      - "/.github/actions/version-framework"
      - "/.github/actions/workflow-run"
      - "/.github/actions/"
    groups:
      github-actions:
        patterns:
          - "*"
