---
version: 2
updates:
  # Enable version updates for pytest_otel
  - package-ecosystem: "pip"
    directory: "resources/scripts/pytest_otel"
    # Check for updates once a month
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "elastic/observablt-ci"
      - "kuisathaverat"

  # Maintain dependencies for GitHub Actions (/.github/workflows)
  # and GitHub composite Actions (/.github/actions)
  # Waiting for supporting wildcards, see https://github.com/dependabot/dependabot-core/issues/5137
  - package-ecosystem: github-actions
    directories:
      - '/'
      - '/.github/actions/*'
    schedule:
      # interval: 'weekly'
      interval: 'daily'
      day: 'sunday'
      time: '22:00'
    reviewers:
      - 'elastic/observablt-ci'
    labels:
      - 'dependencies'
    groups:
      github-actions:
        patterns:
          - '*'
