pull_request_rules:
  - name: Automatic squash and merge on approval with success checks and ready-to-merge label
    conditions:
      - "#approved-reviews-by>=2"
      - check-success=apm-ci/pr-merge
      - check-success=CLA
      - check-success=Test
      - label=ready-to-merge
      - base=master
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: backport patches to 7.x branch
    conditions:
      - base=master
      - label=backport-to-7.x
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - 7.x
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
        labels:
          - "automation"
  - name: Automatic squash and merge on approval with success checks and ready-to-merge label for 7.x
    conditions:
      - check-success=apm-ci/pr-merge
      - check-success=CLA
      - check-success=Test
      - base=7.x
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
  - name: delete upstream branch after merging changes
    conditions:
      - merged
      - label=automation
      - base~=^update-.*-version
    actions:
      delete_head_branch:
  - name: assign PRs
    conditions:
      - -merged
      - -closed
      - "#assignee=0"
    actions:
      assign:
        add_users:
          - "{{author}}"
  - name: notify the backport has not been merged yet
    conditions:
      - -merged
      - -closed
      - author=mergify[bot]
      - check-success=CLA
      - schedule=Mon-Fri 13:00-14:00[Europe/Paris]
      - updated-at<2 days ago
      - "#assignee>=1"
    actions:
      comment:
        message: |
          This pull request has not been merged yet. Could you please review and merge it @{{ assignee | join(', @') }}? 🙏
