queue_rules:
  - name: default
    conditions:
      - check-success=build
      - check-success=licenses
      - check-success=pre-commit

pull_request_rules:
  - name: Automatic squash and merge on approval with success checks and ready-to-merge label
    conditions:
      - "#approved-reviews-by>=2"
      - check-success=apm-ci/pr-merge
      - check-success=CLA
      - check-success=Test
      - label=ready-to-merge
      - base=main
    actions:
      queue:
        method: squash
        name: default
  - name: delete upstream branch that has been merged or closed
    conditions:
      - or:
        - merged
        - closed
      - and:
        - label=automation
        - base~=^update.*
    actions:
      delete_head_branch:
  - name: assign PRs
    conditions:
      - -merged
      - -closed
      - "#assignee=0"
    actions:
      assign:
        add_users:
          - "{{author}}"
