# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "elastic/windows-2016-x86_64"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "6144"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "30"]
  end

  $script = <<-SCRIPT
  Write-Host "Installing chocolatey..."
  Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  Write-Host "Installing java and docker..."
  & choco install adoptopenjdk8 docker-for-windows -y --no-progress
  Write-Host "Downloading swarm..."
  (New-Object Net.WebClient).DownloadFile('https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.9/swarm-client-3.9.jar', 'swarm-client.jar')
  Start-Job { java -jar swarm-client.jar -labels "windows-2016 immutable" -master http://10.0.2.2:18080 }
  SCRIPT

  config.vm.provision "shell", inline: $script
end
