# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "elastic/windows-2016-x86_64"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "6144"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "30"]
  end

  config.vm.provision "shell", privileged: "false", powershell_elevated_interactive: "true", path: "../setup.ps1"
  config.vm.provision "shell", privileged: "false", powershell_elevated_interactive: "true", path: "../swarm.bat"
end
