---
name: 'Send a Slack message'
description: 'Get the credentials from the Vault and send an Slack message.'
inputs:
  url:
    description: 'Vault URL'
    required: true
  roleId:
    description: 'Vault role ID'
    required: true
  secretId:
    description: 'Vault secret ID'
    required: true
  channel:
    description: 'Slack channel'
    required: true
  message:
    description: |
      Slack message on Markdown format. Multiline messages must be escaped using URL encoding.
      https://github.com/orgs/community/discussions/26288

      This is an example how to escape a multiline message in Python:
      ```Python
      from urllib.parse import quote

      message = quote("""
      Hello!!!
      This is a multiline message
      """) # Multiline message
      ```
    required: false
  payload:
    description: 'Slack Payload'
    required: false
  mask:
    description: 'True to mask the Slack message on the logs'
    required: false
    default: 'true'
  urlEncoded:
    description: 'True if the message is URL encoded'
    required: false
    default: 'true'
  threadTimestamp:
    description: 'The timestamp on the message that was posted into Slack when using bot token'
    required: false
outputs:
  threadTimestamp:
    description: 'The timestamp on the message that was posted into Slack when using bot token'
    value: ${{ steps.set_outputs.outputs.threadTimestamp }}
  bar:
    description: test
    value: ${{ steps.set_outputs.outputs.bar }}
runs:
  using: "composite"
  steps:
    - name: Get the Slack token from Vault
      uses: hashicorp/vault-action@v2.8.0
      with:
        url: ${{ inputs.url }}
        roleId: ${{ inputs.roleId }}
        secretId: ${{ inputs.secretId }}
        method: approle
        secrets: |
          secret/observability-team/ci/stack-integartion-token integration_token | SLACK_BOT_TOKEN

    - name: prepare message
      shell: python
      id: prepare
      env:
        MESSAGE: ${{ inputs.message }}
        MASK: ${{ inputs.mask }}
        URL_ENCODED: ${{ inputs.urlEncoded }}
        PAYLOAD: ${{ inputs.payload }}
        THREAD_TIMESTAMP: ${{ inputs.threadTimestamp }}
      run: |
        # Prepare Slack API payload.
        # Documentation about the payload format.
        # https://api.slack.com/reference/messaging/payload
        # https://app.slack.com/block-kit-builder
        # https://api.slack.com/reference/surfaces/formatting
        # https://api.slack.com/reference/surfaces/formatting#escaping
        import json
        import os
        from urllib.parse import unquote

        if os.environ["MESSAGE"]:
          message = os.environ.get('MESSAGE', 'No message')
          if os.environ['URL_ENCODED'] == 'true':
            message = unquote(message)
          message = '\n'.join(line.strip() for line in message.splitlines())
          json_data = {
            "text": message,
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": message
                }
              }
            ]
          }
        elif os.environ["PAYLOAD"]:
          json_data = json.loads(os.environ["PAYLOAD"])
        else:
          raise Exception("Either message or payload must be set.")

        if os.environ["THREAD_TIMESTAMP"]:
          json_data['thread_ts'] = os.environ["THREAD_TIMESTAMP"]

        with open(os.environ.get('GITHUB_OUTPUT'), "a") as f:
          f.write("payload={}".format(json.dumps(json_data)))
        if os.environ.get('MASK') == 'true':
          print("::add-mask::{}".format(json.dumps(json_data)))
    - name: Processing message
      id: slack_message
      uses: slackapi/slack-github-action@v1.25.0
      with:
        channel-id: '${{ inputs.channel }}'
        payload: |
          ${{ steps.prepare.outputs.payload }}
      env:
        SLACK_BOT_TOKEN: ${{ env.SLACK_BOT_TOKEN }}
    - name: Set environment and outputs
      uses: actions/github-script@v7
      id: set_outputs
      with:
        script: |
          core.exportVariable('SLACK_BOT_TOKEN', '')
          core.setOutput('threadTimestamp', '${{ steps.slack_message.outputs.thread_ts }}')
          core.setOutput('bar', 'baz')
