---
name: synthetics-stack-e2e-run
description: |
  This action is part of the synthetics-stack-e2e action.

  It first creates a Kibana docker image, then it deploys an ESS cluster with the created docker image,
  and finally it runs the Synthetics Stack E2E tests against the deployed ESS cluster.

inputs:
  buildkite-pipeline-slug:
    description: 'The Buildkite pipeline slug'
    default: kibana-pr-synthetics-stack-e2e-ci
    required: false
  vault-url:
    description: 'Vault URL'
    required: true
  vault-role-id:
    description: 'Vault role ID'
    required: true
  vault-secret-id:
    description: 'Vault secret ID'
    required: true
  comment-id:
    description: 'The GitHub Comment ID'
    default: ${{ github.event.comment.id }}
  commit-sha:
    description: 'The commit SHA'
    required: false
  pr-number:
    description: 'The PR number'
    default: ${{ github.event.issue.number }}
    required: false
  user:
    description: 'The GitHub user that triggered the workflow'
    default: ${{ github.triggering_actor }}
    required: true

runs:
  using: composite
  steps:
    - uses: elastic/apm-pipeline-library/.github/actions/github-token@current
      with:
        url: ${{ inputs.vault-url }}
        roleId: ${{ inputs.vault-role-id }}
        secretId: ${{ inputs.vault-secret-id }}

    - uses: elastic/apm-pipeline-library/.github/actions/setup-git@current
      with:
        username: ${{ env.GIT_USER }}
        email: ${{ env.GIT_EMAIL }}
        token: ${{ env.GITHUB_TOKEN }}

    - uses: elastic/apm-pipeline-library/.github/actions/setup-oblt-cli@current
      with:
        github-token: ${{ env.GITHUB_TOKEN }}

    - name: Is an Elastic member?
      id: is_elastic_member
      uses: elastic/apm-pipeline-library/.github/actions/is-member-elastic-org@current
      with:
        username: ${{ inputs.user }}
        token: ${{ env.GITHUB_TOKEN }}

    - name: Notify with a reaction
      continue-on-error: true
      uses: elastic/apm-pipeline-library/.github/actions/comment-reaction@current
      with:
        repository: ${{ github.repository }}
        commentId: ${{ inputs.comment-id }}
        emoji: ${{ steps.is_elastic_member.outputs.result && '+1' || '-1' }}
        token: ${{ env.GITHUB_TOKEN }}

    - name: Exit if not an Elastician comment
      if: steps.is_elastic_member.outputs.result == 'false'
      run: exit 1;
      shell: bash

    - uses: elastic/apm-pipeline-library/.github/actions/docker-login@current
      with:
        registry: docker.elastic.co
        secret: secret/observability-team/ci/docker-registry/prod
        url: ${{ inputs.vault-url }}
        roleId: ${{ inputs.vault-role-id }}
        secretId: ${{ inputs.vault-secret-id }}

    - uses: elastic/apm-pipeline-library/.github/actions/kibana-docker-image@current
      id: kibana-docker-image
      with:
        github-repository: ${{ github.repository }}
        git-ref: ${{ inputs.commit-sha || format('refs/pull/{0}/head', inputs.pr-number) }}

    - name: Create cluster
      id: create-cluster
      run: >-
        ${{ github.action_path }}/create-cluster.sh
        ${{ steps.kibana-docker-image.outputs.kibana-docker-image }}
        ${{ steps.kibana-docker-image.outputs.kibana-stack-version }}
      shell: bash

    # - uses: elastic/apm-pipeline-library/.github/actions/buildkite@current # TODO: Use this when PR is merged
    - uses: reakaleek/apm-pipeline-library/.github/actions/buildkite@main
      id: buildkite
      with:
        vaultUrl: ${{ inputs.vault-url }}
        vaultRoleId: ${{ inputs.vault-role-id }}
        vaultSecretId: ${{ inputs.vault-secret-id }}
        pipeline: ${{ inputs.buildkite-pipeline-slug }}
        triggerMessage: Triggered by PR ${{ github.repository }}#${{ inputs.pr-number }}
        pipelineBranch: use-kibana-url
        waitFor: true
        buildEnvVars: |
          OBLT_CLUSTER_STATE_SECRET_PATH=secret/observability-team/ci/test-clusters/${{ steps.create-cluster.outputs.cluster-name }}/cluster-state
          KIBANA_PR_URL=${{ github.server_url }}/${{ github.repository }}/pull/${{ inputs.pr-number }}

    - if: always() && steps.buildkite.outputs.build
      name: Add notice message
      run: |
        echo "::notice title=${TITLE}::${BUILDKITE_BUILD_URL}"
      shell: bash
      env:
        BUILDKITE_BUILD_URL: ${{ steps.buildkite.outputs.build }}
        TITLE: Synthetics Stack E2E Buildkite Build

    - if: always() && steps.create-cluster.outcome == 'success'
      name: Destroy cluster
      run: >-
        ${{ github.action_path }}/destroy-cluster.sh
        ${{ steps.create-cluster.outputs.cluster-name }}
      shell: bash
