bundle:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-custom-war"
  vendor: "Victor Martinez"
  title: "Jenkins WAR - APM"
buildSettings:
  pom: pom.xml
  pomIgnoreRoot: true
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: 2.176.1
