apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
  spec:
    containers:
    - name: java
      image: docker.pkg.github.com/v1v/observability-ci/apm-pipeline-library1:latest
      command:
      - cat
      tty: true
      env:
      - name: CONTAINER_ENV_VAR
        value: java
