apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
  spec:
    containers:
    - name: 'jnlp'
      image: 'jenkinsci/jnlp-slave:latest'
      workingDir: '/home/jenkins'
    - name: java
      image: adoptopenjdk:8-openj9-bionic
      command:
      - cat
      tty: true
      env:
      - name: CONTAINER_ENV_VAR
        value: java
