apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: apm-ci
    project: apm-pipeline-library
spec:
  containers:
  - name: shell
    image: openjdk:18-jdk-alpine
    command:
    - sleep
    args:
    - infinity
