apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: k8s-test
    some-label: some-label-value
spec:
  containers:
  - name: shell
    image: openjdk:18-jdk-alpine
    command:
    - sleep
    args:
    - infinity
