---
## This is the file that contains what projects should bump their elastic stack
## release versions.
##
## The data structure:
##  repo: the repository name
##  script: the relative path to the script in charge to bump the version
##  branches: the list of branches that should benefit from this automation.
##  enabled: whether the automation has been enabled for this project.
##  labels: list of GitHub labels to be added to the Pull Request (comma separated).
##
projects:
  - repo: apm-pipeline-library
    script: .ci/bump-stack-release-version.sh
    branches:
      - master
    enabled: true
    labels: dependency
  - repo: apm-integration-testing
    script: .ci/bump-stack-release-version.sh
    branches:
      - master
      - 7.x
    enabled: true
    labels: dependency
  - repo: observability-test-environments
    script: .ci/bump-stack-release-version.sh
    branches:
      - dev
      - edge
      - master
      - release
    enabled: false
    labels: dependency
