---
## This is the file that contains what projects should bump their elastic stack
## release versions.
##
## The data structure:
##  repo: the repository name
##  script: the relative path to the script in charge to bump the version
##  branches: the list of branches that should benefit from this automation.
##  enabled: whether the automation has been enabled for this project.
##  labels: list of GitHub labels to be added to the Pull Request (comma separated).
##  title: the PR title, empty if you'd like to use the default one.
##  assign: A comma-separated list (no spaces around the comma) of GitHub handles to assign to this pull request. Optional.
##  reviewer: A comma-separated list (no spaces around the comma) of GitHub handles to request a review from. Optional.
##
projects:
  - repo: apm-pipeline-library
    script: .ci/bump-stack-release-version.sh
    branches:
      - main
    enabled: true
    labels: dependency
    reviewer: elastic/observablt-ci
  - repo: apm-integration-testing
    script: .ci/bump-stack-release-version.sh
    branches:
      - main
      - 7.x
    enabled: true
    labels: dependency
    reviewer: elastic/observablt-ci
  - repo: azure-vm-extension
    script: .ci/bump-stack-release-version.sh
    branches:
      - main
    enabled: true
    labels: dependency
    reviewer: elastic/integrations-platforms
  - repo: apm-agent-rum-js
    script: .ci/bump-stack-release-version.sh
    branches:
      - main
    enabled: true
    labels: dependency
    title: "chore: update elastic stack release version"
