---
## This is the file that contains what projects should bump their Golang
## release versions.
##
## The data structure:
##  repo: the repository name
##  script: the relative path to the script in charge to bump the version
##  branches: the list of branches that should benefit from this automation.
##  enabled: whether the automation has been enabled for this project.
##  labels: list of GitHub labels to be added to the Pull Request (comma separated).
##  title: the PR title, empty if you'd like to use the default one.
##
projects:
  - repo: apm-pipeline-library
    script: .ci/bump-go-release-version.sh
    branches:
      - master
    enabled: true
    labels: dependency
  - repo: apm-integration-testing
    script: .ci/bump-go-release-version.sh
    branches:
      - master
      - 7.x
    enabled: true
    labels: dependency
  - repo: beats
    script: .ci/bump-go-release-version.sh
    branches:
      - master
    enabled: true
    labels: dependency
  - repo: fleet-server
    script: .ci/bump-go-release-version.sh
    branches:
      - master
    enabled: true
    labels: dependency
  - repo: golang-crossbuild
    script: .ci/bump-go-release-version.sh
    branches:
      - master
    enabled: true
    labels: dependency
