---
## This is the file that contains what projects should bump their Golang
## release versions.
##
## The data structure:
##  repo: the repository name
##  script: the relative path to the script in charge to bump the version
##  branches: the list of branches that should benefit from this automation.
##  enabled: whether the automation has been enabled for this project.
##  labels: list of GitHub labels to be added to the Pull Request (comma separated).
##  title: the PR title, empty if you'd like to use the default one.
##  assign: A comma-separated list (no spaces around the comma) of GitHub handles to assign to this pull request. Optional.
##  reviewer: A comma-separated list (no spaces around the comma) of GitHub handles to request a review from. Optional.
##
projects:
  - repo: apm-pipeline-library
    script: .ci/bump-go-release-version.sh
    branches:
      - main
    enabled: true
    labels: dependency
    reviewer: elastic/observablt-robots-on-call
  - repo: apm-integration-testing
    script: .ci/bump-go-release-version.sh
    branches:
      - main
      - 7.x
    enabled: true
    labels: dependency
    reviewer: elastic/observablt-robots-on-call
  - repo: beats
    script: .ci/bump-go-release-version.sh
    branches:
      - main
    enabled: true
    labels: dependency,backport-skip
  - repo: elastic-agent
    script: .ci/bump-go-release-version.sh
    branches:
      - main
    enabled: true
    labels: dependency,backport-skip
  - repo: fleet-server
    script: .ci/bump-go-release-version.sh
    branches:
      - main
    enabled: true
    labels: dependency,backport-skip
  - repo: golang-crossbuild
    script: .ci/bump-go-release-version.sh
    branches:
      - main
    enabled: true
    labels: dependency
  - repo: observability-robots
    script: .ci/bump-go-release-version.sh
    branches:
      - main
    enabled: true
    labels: dependency
    reviewer: elastic/observablt-robots-on-call
