#!/usr/bin/env groovy

@Library('apm@current') _

pipeline {
  agent any
  environment {
    BASE_DIR="src/github.com/elastic/apm-pipeline-library"
    NOTIFY_TO = credentials('notify-to')
    JOB_GCS_BUCKET = credentials('gcs-bucket')
    PIPELINE_LOG_LEVEL = 'INFO'
  }
  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
  }
  stages {
    stage('Initializing'){
      agent { label 'linux && immutable' }
      options { skipDefaultCheckout() }
      environment {
        PATH = "${env.PATH}:${env.WORKSPACE}/bin"
      }
      stages {
        /**
         Checkout the code and stash it, to use it on other stages.
        */
        stage('Checkout') {
          steps {
            deleteDir()
            gitCheckout(basedir: "${BASE_DIR}")
            stash allowEmpty: true, name: 'source', useDefaultExcludes: false
          }
        }

        stage('Check Licenses') {
          steps {
            deleteDir()
            unstash 'source'
            dir("${BASE_DIR}"){
              catchError(
                  buildResult: 'SUCCESS',
                  stageResult: 'UNSTABLE',
                  message: 'Some files does not contain license'
                  ) {
                checkLicenses()
              }
            }
          }
        }
        /**
         Checkout the code and stash it, to use it on other stages.
        */
        stage('Test') {
          steps {
            deleteDir()
            unstash 'source'
            dir("${BASE_DIR}"){
              sh './mvnw clean test --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
            }
          }
          post {
            always {
              junit(allowEmptyResults: true,
                keepLongStdio: true,
                testResults: "${BASE_DIR}/target/surefire-reports/junit-*.xml,${BASE_DIR}/target/surefire-reports/TEST-*.xml")
            }
          }
        }

        stage('Check Pipelines') {
          steps {
            validateDeclarativePipeline '.ci/Jenkinsfile'
            validateDeclarativePipeline '.ci/buildDockerImages.groovy'
            validateDeclarativePipeline '.ci/dockerImagesESLatest.groovy'
            validateDeclarativePipeline '.ci/dockerImagesOpbeans.groovy'
            validateDeclarativePipeline '.ci/schedule-daily.groovy'
            validateDeclarativePipeline '.ci/schedule-weekly.groovy'
            validateDeclarativePipeline 'resources/JenkinsfileTemplate.groovy'
          }
        }
      }
    }
  }
  post {
    always {
      notifyBuildResult()
    }
  }
}

def checkLicenses(){
  docker.image('golang:1.12').inside("-e HOME=${WORKSPACE}/${BASE_DIR}"){
    sh(label: "Check Licenses", script: '''
    go get -u github.com/elastic/go-licenser
    go-licenser -d -ext .groovy''')
  }
}
