// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

@Library('apm@main') _

pipeline {
  agent { label 'k8s' }
  environment {
    REPO = 'apm-pipeline-library'
    BASE_DIR = "src/github.com/elastic/${env.REPO}"
    NOTIFY_TO = credentials('notify-to')
    PIPELINE_LOG_LEVEL = 'INFO'
    MAVEN_CONFIG = "${params.MAVEN_CONFIG}"
    LANG = "C.UTF-8"
    LC_ALL = "C.UTF-8"
    SLACK_CHANNEL = '#observablt-bots'
    JOB_GCS_BUCKET = 'apm-ci-temp'
    JOB_GCS_CREDENTIALS = 'apm-ci-gcs-plugin-file-credentials'
  }
  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    disableConcurrentBuilds(abortPrevious: isPR())
  }
  triggers {
    issueCommentTrigger("(${obltGitHubComments()}|^run infra tests|^/test all)")
  }
  parameters {
    string(name: 'MAVEN_CONFIG', defaultValue: '', description: 'Additional maven options.')
  }
  stages {
    /**
     Checkout the code and stash it, to use it on other stages.
    */
    stage('Checkout') {
      options { skipDefaultCheckout() }
      steps {
        withGithubNotify(context: 'Checkout') {
          pipelineManager([ cancelPreviousRunningBuilds: [ when: 'PR' ] ])
          deleteDir()
          gitCheckout(basedir: "${BASE_DIR}")
          stash allowEmpty: true, name: 'source', useDefaultExcludes: false
        }
      }
    }
    stage('Check Pipelines') {
      options { skipDefaultCheckout() }
      steps {
        withGithubNotify(context: 'Check Pipelines') {
          dir("${BASE_DIR}"){
            validateDeclarativePipeline '.ci/Jenkinsfile'
            validateDeclarativePipeline '.ci/buildBeatsDockerImages.groovy'
            validateDeclarativePipeline '.ci/buildDockerImages.groovy'
            validateDeclarativePipeline '.ci/chatops.groovy'
            validateDeclarativePipeline '.ci/buildDockerImages.groovy'
            validateDeclarativePipeline '.ci/dockerImagesOpbeans.groovy'
            validateDeclarativePipeline '.ci/jobdsl-generator.groovy'
            validateDeclarativePipeline '.ci/schedule-daily.groovy'
            validateDeclarativePipeline '.ci/schedule-weekly.groovy'
            validateDeclarativePipeline '.ci/validateWorkersBeatsCi.groovy'
            validateDeclarativePipeline 'resources/JenkinsfileTemplate.groovy'
          }
        }
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult(prComment: true, slackComment: true, analyzeFlakey: true, jobName: getFlakyJobName(withBranch: 'main'))
    }
  }
}
