// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

@Library('apm@master') _

pipeline {
  agent {
    kubernetes {
      yamlFile '.ci/k8s/build.yaml'
    }
  }
  environment {
    REPO = 'apm-pipeline-library'
    BASE_DIR = "src/github.com/elastic/${env.REPO}"
    NOTIFY_TO = credentials('notify-to')
    PIPELINE_LOG_LEVEL = 'INFO'
    MAVEN_CONFIG = "${params.MAVEN_CONFIG}"
    LANG = "C.UTF-8"
    LC_ALL = "C.UTF-8"
  }
  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
  }
  triggers {
    issueCommentTrigger('(?i).*(?:jenkins\\W+)?run\\W+(?:the\\W+)?tests(?:\\W+please)?.*')
  }
  parameters {
    string(name: 'MAVEN_CONFIG', defaultValue: '', description: 'Additional maven options.')
    booleanParam(name: 'make_release', defaultValue: "false", description: "Enable perform a Release")
  }
  stages {
    /**
     Checkout the code and stash it, to use it on other stages.
    */
    stage('Checkout') {
      options { skipDefaultCheckout() }
      steps {
        withGithubNotify(context: 'Checkout') {
          debugCommand()
          pipelineManager([ cancelPreviousRunningBuilds: [ when: 'PR' ] ])
          deleteDir()
          gitCheckout(basedir: "${BASE_DIR}")
          stash allowEmpty: true, name: 'source', useDefaultExcludes: false
          dir("${BASE_DIR}"){
            setEnvVar('TEST_INFRA', isGitRegionMatch(patterns: [ '(^test-infra|^resources\\/scripts\\/jenkins)\\/.*' ], shouldMatchAll: false))
            setEnvVar('IS_DOCKER_CHANGES', isGitRegionMatch(patterns: [ '^.ci\\/docker\\/build\\/.*' ], shouldMatchAll: false))
            setEnvVar('IS_DOCKER_CHANGES_ONLY', isGitRegionMatch(patterns: [ '^.ci\\/docker\\/build\\/.*' ], shouldMatchAll: true))
          }
        }
      }
    }
    stage('Docker image') {
      when { expression { return env.IS_DOCKER_CHANGES == "true" } }
      steps {
        /**
        sh(label: 'Test Docker container', script: 'make -C .ci/docker test-build')
        retry(3){
          sh(label: 'Push Docker images', script: "VERSION=${GIT_BASE_COMMIT} make -C .ci/docker push-build-${VERSION}")
        }
        dir('pr') {
          // git ''
          // edit yaml file
          // git add commit
          // githubCreatePullRequest(title: 'Validate docker changes in PR-XYZ', labels: 'automation')
        }
        whenFalse(env.IS_DOCKER_CHANGES_ONLY != "true") {
          error('IMPORTANT: changes related to dockerfiles should be validated, please look at the just generated PR with those changes.')
        }
        */
        echo 'TBD'
      }
    }
    stage('Check Licenses') {
      agent { label 'ubuntu && immutable' } // TODO: required docker CLI in the pod template
      steps {
        withGithubNotify(context: 'Check Licenses') {
          deleteDir()
          unstash 'source'
          dir("${BASE_DIR}"){
            catchError(
                buildResult: 'SUCCESS',
                stageResult: 'UNSTABLE',
                message: 'Some files does not contain license'
                ) {
              checkLicenses(skip: true, junit:true, ext: '.groovy')
            }
          }
        }
      }
    }
    stage('Check pre-commit') {
      agent { label 'ubuntu && immutable' } // TODO: required docker CLI in the pod template
      when { expression { return env.IS_DOCKER_CHANGES_ONLY != "true" } }
      steps {
        withGithubNotify(context: 'Check pre-commit', tab: 'tests') {
          deleteDir()
          unstash 'source'
          dir("${BASE_DIR}"){
            preCommit(commit: "${GIT_BASE_COMMIT}", junit: true)
          }
        }
      }
    }
    /**
     Checkout the code and stash it, to use it on other stages.
    */
    stage('Test') {
      steps {
        container('java') {
          withGithubNotify(context: 'Test', description: 'UTs', tab: 'tests') {
            debugCommand()
            deleteDir()
            unstash 'source'
            dir("${BASE_DIR}"){
              sh './mvnw clean test --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
            }
          }
        }
      }
      post {
        always {
          archiveArtifacts(allowEmptyArchive: true, artifacts: '${BASE_DIR}/**/mail-out-test*.html')
          junit(allowEmptyResults: true,
            keepLongStdio: true,
            testResults: "${BASE_DIR}/target/surefire-reports/junit-*.xml,${BASE_DIR}/target/surefire-reports/TEST-*.xml")
        }
      }
    }
    stage('Check Pipelines') {
      steps {
        container('java') {
          withGithubNotify(context: 'Check Pipelines') {
            deleteDir()
            unstash 'source'
            debugCommand()
            dir("${BASE_DIR}"){
              validateDeclarativePipeline '.ci/Jenkinsfile'
              validateDeclarativePipeline '.ci/buildBeatsDockerImages.groovy'
              validateDeclarativePipeline '.ci/buildDockerImages.groovy'
              validateDeclarativePipeline '.ci/dockerImagesOpbeans.groovy'
              validateDeclarativePipeline '.ci/schedule-daily.groovy'
              validateDeclarativePipeline '.ci/schedule-weekly.groovy'
              validateDeclarativePipeline 'resources/JenkinsfileTemplate.groovy'
            }
          }
        }
      }
    }
    stage('Test infra') {
      when {
        beforeAgent true
        anyOf {
          expression { return env.TEST_INFRA == "true" }
          branch 'master'
        }
      }
      steps {
        container('java') {
          withGithubNotify(context: 'Test infra') {
            deleteDir()
            unstash 'source'
            debugCommand()
            dir("${BASE_DIR}"){
              sh script: './resources/scripts/jenkins/apm-ci/test.sh'
              sh script: './resources/scripts/jenkins/build.sh'
            }
          }
        }
      }
      post {
        always {
          junit(allowEmptyResults: true, keepLongStdio: true, testResults: "${BASE_DIR}/**/target/junit-test-infra.xml")
        }
      }
    }
    stage('Super-linter') {
      agent { label 'ubuntu && immutable' } // TODO: required docker CLI in the pod template
      steps {
        withGithubNotify(context: 'Check super-linter', tab: 'tests') {
          deleteDir()
          unstash 'source'
          debugCommand()
          dir("${BASE_DIR}"){
            superLinter(failNever: true, junit: false)
          }
        }
      }
    }
    stage('Release') {
      agent { label 'ubuntu && immutable' } // TODO: required docker CLI in the pod template
      environment {
        // gren and other tools are in the .ci/scripts folder.
        PATH = "${env.WORKSPACE}/${env.BASE_DIR}/.ci/scripts:${env.PATH}"
      }
      when {
        expression {
          return params.make_release
        }
      }
      steps {
        container('java') {
          deleteDir()
          unstash 'source'
          dockerLogin(secret: "secret/apm-team/ci/docker-registry/prod",
            registry: "docker.elastic.co"
          )
          dir("${BASE_DIR}"){
            setupAPMGitEmail(global: false)
            sh(label: 'Performing the Release', script: './resources/scripts/jenkins/release-perform.sh')
            sleep 30 //wait for changes available
            withCredentials([string(credentialsId: '2a9602aa-ab9f-4e52-baf3-b71ca88469c7', variable: 'GREN_GITHUB_TOKEN')]) {
              sh(label: 'Creating Release Notes', script: './resources/scripts/jenkins/release-notes.sh')
              sh(label: 'Add changelog', script: '''#!/bin/bash
                git add CHANGELOG.md
                git commit -m "docs: update CHANGELOG.md"
              ''')
            }
            gitPush()
            gitCreateTag(tag: 'current', tagArgs: '--force', pushArgs: '--force')
          }
        }
      }
    }
  }
  post {
    cleanup {
      debugCommand()
      notifyBuildResult(prComment: true)
    }
  }
}

def debugCommand() {
  sh '''
    ls -ltrah
    pwd
    env | sort
    whoami || true
    touch file.txt
  '''
}
