---
- job:
    name: apm-shared/apm-dependabot-pipeline
    display-name: Dependabot Pipeline
    description: Run dependabot for all the projects listed
    view: APM-CI
    project-type: pipeline
    pipeline-scm:
      script-path: .ci/dependabot.groovy
      scm:
        - git:
            url: git@github.com:elastic/apm-pipeline-library.git
            refspec: +refs/heads/*:refs/remotes/origin/* +refs/pull/*/head:refs/remotes/origin/pr/*
            wipe-workspace: 'True'
            name: origin
            shallow-clone: true
            credentials-id: f6c7695a-671e-4f4f-a331-acdce44ff9ba
            reference-repo: /var/lib/jenkins/.git-references/apm-pipeline-library.git
            branches:
              - master
