#!/bin/sh
# Basic credential helper,
# it uses the environment variables DOCKER_REGISTRY, DOCKER_USER, and DOCKER_PASSWORD to authenticate.
# inspired on https://gist.github.com/jasonk/480d87b49e4c8caf51932f184ff764b2

die() {
  echo "$@" 1>&2
  exit 1
}

if [ -z "$DOCKER_REGISTRY" ]; then die "DOCKER_REGISTRY not set in environment"; fi
case "$1" in
  get)
    read -r HOST
    if [ "$HOST" = "$DOCKER_REGISTRY" ]; then
      printf '{"ServerURL":"%s","Username":"%s","Secret":"%s"}\n' "$HOST" "$DOCKER_USER" "$DOCKER_PASSWORD"
    else
      die "No credentials available for $HOST"
    fi
    ;;
  store)
    ;;
  erase)
    ;;
  *)
    die "Unsupported operation"
    ;;
esac
