name: 'Oblt-cli destroy cluster'
description: 'Run the oblt-cli wrapper to destroy the given cluster'
inputs:
  cluster-name:
    description: 'The cluster name'
    required: false
  cluster-info-file:
    description: 'The cluster info file (absolute path)'
    required: false
  github-token:
    description: 'The GitHub access token.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Process inputs
      uses: actions/github-script@v6
      with:
        script: |
          const clusterName = core.getInput('cluster-name')
          const clusterInfoFile = core.getInput('cluster-info-file')

          if (clusterName && clusterInfoFile) {
            core.setFailed(`Either cluster-name or cluster-info-file but no both`)
          }

          var cluster = clusterName

          if (clusterInfoFile) {
            const fs = require('fs')
            const data = fs.readFileSync(clusterInfoFile, 'utf8')
            const jsonObject = JSON.parse(data)
            if (jsonObject && jsonObject.ClusterName === undefined) {
              core.setFailed(`cluster-info-file does not contain the field ClusterName`)
            }
            cluster = jsonObject.ClusterName
          }

          if (cluster.trim().length === 0) {
            core.setFailed(`cluster name is empty`)
          }
          core.exportVariable('CLUSTER_NAME', `${cluster}`)

    - uses: elastic/apm-pipeline-library/.github/actions/oblt-cli@current
      with:
        command: cluster destroy --cluster-name "${{ env.CLUSTER_NAME }}" --force
        token: ${{ inputs.github-token }}
