name: 'Oblt-cli destroy cluster'
description: 'Run the oblt-cli wrapper to destroy the given cluster'
inputs:
  cluster-name:
    description: 'The cluster name'
    required: false
  github-token:
    description: 'The GitHub access token.'
    required: true
runs:
  using: "composite"
  steps:
    # TODO: avoid destroying a golden cluster
    - uses: elastic/apm-pipeline-library/.github/actions/oblt-cli@current
      with:
        command: cluster destroy --cluster-name "${{ env.CLUSTER_NAME }}" --force
        token: ${{ inputs.github-token }}
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
