name: 'Oblt-cli destroy cluster'
description: 'Run the oblt-cli wrapper to destroy the given cluster'
inputs:
  cluster-name:
    description: 'The cluster name'
    required: false
  cluster-info-file:
    description: 'The cluster info file (absolute path)'
    required: false
  github-token:
    description: 'The GitHub access token.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Process inputs
      uses: actions/github-script@v6
      env:
        CLUSTER_NAME_INPUT: ${{ inputs.cluster-name }}
        CLUSTER_INFO_FILE_INPUT: ${{ inputs.cluster-info-file }}
      with:
        script: |
          const clusterNameInput = process.env.CLUSTER_NAME_INPUT
          const clusterInfoFile = process.env.CLUSTER_INFO_FILE_INPUT

          if (clusterNameInput && clusterInfoFile) {
            core.setFailed(`Either cluster-name or cluster-info-file but no both`)
          }

          var clusterName = clusterNameInput

          if (clusterInfoFile) {
            const fs = require('fs')
            const data = fs.readFileSync(clusterInfoFile, 'utf8')
            const jsonObject = JSON.parse(data)
            if (jsonObject && jsonObject.ClusterName === undefined) {
              core.setFailed(`cluster-info-file does not contain the field ClusterName`)
            }
            clusterName = jsonObject.ClusterName
          }

          if (clusterName.trim().length === 0) {
            core.setFailed(`cluster name is empty`)
          }

          console.log(`clusterName is "${clusterName}"`)
          core.exportVariable('CLUSTER_NAME', `${clusterName}`)

    - uses: elastic/apm-pipeline-library/.github/actions/oblt-cli@current
      with:
        command: cluster destroy --cluster-name "${{ env.CLUSTER_NAME }}" --force
        token: ${{ inputs.github-token }}
