name: 'Oblt-cli destroy cluster'
description: 'Run the oblt-cli wrapper to destroy the given cluster'
inputs:
  cluster-name:
    description: 'The cluster name'
    required: false
  cluster-info-file:
    description: 'The cluster info file (absolute path)'
    required: false
  github-token:
    description: 'The GitHub access token.'
    required: true
  username:
    description: 'Username to show in the deployments with oblt-cli, format: [a-z0-9]'
    default: 'obltmachine'
    required: false
runs:
  using: "composite"
  steps:
    - uses: elastic/apm-pipeline-library/.github/actions/oblt-cli-cluster-name-validation@current
      id: validation
      with:
        cluster-name: ${{ inputs.cluster-name }}
        cluster-info-file: ${{ inputs.cluster-info-file }}

    - uses: elastic/apm-pipeline-library/.github/actions/oblt-cli@current
      with:
        command: cluster destroy --cluster-name "${{ steps.validation.outputs.cluster-name }}" --force
        token: ${{ inputs.github-token }}
        username: ${{ inputs.username }}
