---

name: check-dependent-jobs
description: |
  Evaluates the combined the status results of the provided needs context.
inputs:
  needs:
    required: true
    description: needs context as JSON string
outputs:
  isSuccess:
    description: The evaluated result of all provided jobs in the needs context.
    value: ${{ steps.check.outputs.isSuccess }}
  status:
    description: One of success or failure.
    value: ${{ steps.check.outputs.status }}
runs:
  using: composite
  steps:
    - id: check
      uses: actions/github-script@v7
      env:
        NEEDS: ${{ inputs.needs }}
      with:
        script: |
          const needs = JSON.parse(process.env.NEEDS)
          let allJobsAreSuccess = false
          for (const job in needs) {
            if (!needs[job].success) {
              allJobsAreSuccess = false
              break
            }
          }
          core.setOutput('isSuccess', allJobsAreSuccess)
          core.setOutput('status', allJobsAreSuccess ? "success" : "failure")
