name: 'Oblt-cli cluster credentials'
description: 'Run the oblt-cli wrapper to retrieve the credentials to connect to the given cluster'
inputs:
  cluster-name:
    description: 'The cluster name'
    required: false
  token:
    description: 'The GitHub access token.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup oblt-cli
      uses: elastic/apm-pipeline-library/.github/actions/setup-oblt-cli@current
      with:
        github-token: ${{ inputs.token }}

    - name: run oblt-cli
      run: |
        oblt-cli cluster secrets env --cluster-name ${{ env.CLUSTER_NAME }} --output-file "${ENV_FILE}"
        cat "${ENV_FILE}" >> "${GITHUB_ENV}"
        source ${ENV_FILE}
        for i in $(cat "${ENV_FILE}"|cut -d "=" -f 1); do
          VALUE=$(eval "echo \${$i}")
          echo "::add-mask::${VALUE}"
        done
        rm -f "${ENV_FILE}"
      shell: bash
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
        GITHUB_TOKEN: ${{ inputs.token }}
