name: benchmarks

inputs:
  vaultUrl:
    description: 'Vault URL'
    required: true
  vaultRoleId:
    description: 'Vault role ID'
    required: true
  vaultSecretId:
    description: 'Vault secret ID'
    required: true
  githubToken:
    description: 'GitHub token'
    required: true
  sha:
    description: 'The Git Sha commit'
    required: true

runs:
  using: "composite"
  steps:

  - name: Run benchmark script
    run: .ci/scripts/bench.sh
    shell: bash

  - name: Dump GitHub context
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    run: echo "$GITHUB_CONTEXT"
    shell: bash

  - name: Create GitHub check
    env:
      GH_TOKEN: ${{ inputs.githubToken }}
    run: |
      gh api repos/elastic/apm-pipeline-library/statuses/${{ inputs.sha }} \
      -X POST \
      --input - <<< "{\"state\":\"success\",\"context\": \"benchmark\", \"target_url\": \"https://github.com/elastic/observability-robots-playground/\"}}"
    shell: bash

  - name: Report results
    if: always()
    uses: elastic/apm-pipeline-library/.github/actions/notify-build-status@current
    with:
      vaultUrl: ${{ inputs.vaultUrl }}
      vaultRoleId: ${{ inputs.vaultRoleId }}
      vaultSecretId: ${{ inputs.vaultSecretId }}
      slackChannel: '#on-week-oblt-productivity'
