name: notify-build-status
description: "Notify the build status"

inputs:
  vaultUrl:
    description: Vault URL
    required: true
  vaultRoleId:
    description: Vault role ID
    required: true
  vaultSecretId:
    description: Vault secret ID
    required: true
  slackChannel:
    description: Slack channel
    required: false
  message:
    description: Add additional message
    required: false
  status:
    description: "Explicitly set status. One of success, failure, cancelled, auto. Default: auto"
    required: false
    default: auto

runs:
  using: composite
  steps:
    - name: Prepare data
      id: prepare
      shell: bash
      env:
        JOB_STATUS: "${{ inputs.status == 'auto' && job.status || inputs.status }}"
        MESSAGE: "${{ inputs.message }}"
        PULL_REQUEST_ID: "${{ github.event.pull_request.number }}"
        PULL_REQUEST_SHA: "${{ github.event.pull_request.head.sha }}"
      run: |
        exec node ${{ github.action_path }}/dist/index.js
    - if: ${{ inputs.slackChannel }}
      uses: elastic/apm-pipeline-library/.github/actions/slack-message@current
      with:
        url: ${{ inputs.vaultUrl }}
        roleId: ${{ inputs.vaultRoleId }}
        secretId: ${{ inputs.vaultSecretId }}
        channel: ${{ inputs.slackChannel }}
        payload: ${{ steps.prepare.outputs.slackPayload }}
