name: notify-build-status
description: "Notify the build status"

inputs:
  vaultUrl:
    description: Vault URL
    required: true
  vaultRoleId:
    description: Vault role ID
    required: true
  vaultSecretId:
    description: Vault secret ID
    required: true
  slackChannel:
    description: Slack channel
    required: false

runs:
  using: composite
  steps:
    - uses: hashicorp/vault-action@v2.4.2
      with:
        url: ${{ inputs.vaultUrl }}
        roleId: ${{ inputs.vaultRoleId }}
        secretId: ${{ inputs.vaultSecretId }}
        method: approle
        secrets: |
          secret/observability-team/ci/stack-integartion-token integration_token | SLACK_BOT_TOKEN
    - name: Prepare data
      id: prepare
      shell: python
      run: |
        import os

        job_status = "${{ job.status }}"
        repo_url = "${{ github.server_url }}/${{ github.repository }}"
        pr_number = "${{ github.event.pull_request.number }}"
        run_id = "${{ github.run_id }}"
        run_attempt = "${{ github.run_attempt }}"
        event_name = "${{ github.event_name }}"
        is_pull_request = event_name == 'pull_request'
        sha = "${{ github.event.pull_request.head.sha }}" if is_pull_request else "${{ github.sha }}"

        # Keys taken from https://docs.github.com/en/actions/learn-github-actions/contexts#job-context
        color_status_map = {
          "success": "good",
          "failure": "danger",
          "cancelled": "", # grey
        }

        data = {
          "color": color_status_map[job_status],
          "short_sha": sha[:7],
          "commit_url": f"{repo_url}/pull/{pr_number}/commits/{sha}" if is_pull_request else f"{repo_url}/commit/{sha}",
          "run_url": f"{repo_url}/actions/runs/{run_id}/attempts/{run_attempt}",
          "repo_url": repo_url,
        }

        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            for key, value in data.items():
              print(f'{key}={value}', file=f)
    - if: ${{ inputs.slackChannel }}
      uses: slackapi/slack-github-action@v1.22.0
      with:
        channel-id: '${{ inputs.slackChannel }}'
        payload: |
          {
            "attachments": [
              {
                "pretext": "Workflow <${{ steps.prepare.outputs.repo_url }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}> triggered by <${{ github.server_url }}/${{ github.actor }}|${{ github.actor }}>",
                "color": "${{ steps.prepare.outputs.color }}",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "${{ job.status }}"
                  },
                  {
                    "title": "Event",
                    "short": true,
                    "value": "${{ github.event_name	}}"
                  },
                  {
                    "title": "Ref",
                    "short": true,
                    "value": "`${{ github.ref_name }}`"
                  },
                  {
                    "title": "Commit",
                    "short": true,
                    "value": "<${{ steps.prepare.outputs.commit_url }}|`${{ steps.prepare.outputs.short_sha }}`>"
                  },
                  {
                    "title": "Workflow",
                    "short": false,
                    "value": "<${{ steps.prepare.outputs.run_url }}|${{ github.workflow }} #${{ github.run_number }}>"
                  }
                ],
                "footer": "<${{ steps.prepare.outputs.repo_url }}|${{ github.repository }}>",
                "footer_icon": "https://slack-imgs.com/?c=1&o1=wi32.he32.si&url=https%3A%2F%2Fslack.github.com%2Fstatic%2Fimg%2Ffavicon-neutral.png"
              }
            ]
          }
