---
name: Buildkite Pipeline GitHub Action
description: A GitHub Action for triggering a build on a Buildkite pipeline.
inputs:
  vaultUrl:
    description: 'Vault URL'
    required: true
  vaultRoleId:
    description: 'Vault role ID'
    required: true
  vaultSecretId:
    description: 'Vault secret ID'
    required: true
  secret:
    description: 'Vault secret with the token field.'
    default: secret/observability-team/ci/buildkite-automation
    required: false
  org:
    description: 'BuildKite org to interact with.'
    default: elastic
    required: false
  pipeline:
    description: 'BuildKite pipeline to interact with.'
    required: true
  waitFor:
    description: 'Whether to wait for the build to finish.'
    default: false
    required: false
  printBuildLogs:
    description: 'Whether to wait for the build to finish.'
    default: false
    required: false
  buildEnvVars:
    description: 'Additional environment variables to set on the build.'
    required: false

runs:
  using: "composite"
  steps:
      - uses: hashicorp/vault-action@v2.4.2
        with:
          url: ${{ inputs.vaultUrl }}
          roleId: ${{ inputs.vaultRoleId }}
          secretId: ${{ inputs.vaultSecretId }}
          method: approle
          secrets: |
            ${{ inputs.secret }} token | BUILDKITE_API_ACCESS_TOKEN

      - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
        shell: bash

      - name: Trigger Buildkite pipeline
        run: |
          run.sh \
            '${{ inputs.org }}' \
            '${{ inputs.pipeline }}' \
            '${{ inputs.buildEnvVars }}' \
            '${{ inputs.waitFor }}' \
            '${{ inputs.printBuildLogs }}' \
            '${{ env.BUILDKITE_API_ACCESS_TOKEN }}' \
            '${{ github.sha }}' \
            '${{ github.event.head_commit.author.name }}' \
            '${{ github.event.head_commit.message }}'
        shell: bash
