---
name: Buildkite Pipeline GitHub Action
description: A GitHub Action for triggering a build on a Buildkite pipeline.
inputs:
  vaultUrl:
    description: 'Vault URL'
    required: true
  vaultRoleId:
    description: 'Vault role ID'
    required: true
  vaultSecretId:
    description: 'Vault secret ID'
    required: true
  secret:
    description: 'Vault secret with the token field.'
    default: secret/observability-team/ci/buildkite-automation-v3
    required: false
  org:
    description: 'BuildKite org to interact with.'
    default: elastic
    required: false
  pipeline:
    description: 'BuildKite pipeline to interact with.'
    required: true
  waitFor:
    description: 'Whether to wait for the build to finish.'
    default: false
    required: false
  printBuildLogs:
    description: 'Whether to wait for the build to finish.'
    default: false
    required: false
  buildEnvVars:
    description: 'Additional environment variables to set on the build.'
    required: false
  pipelineBranch:
    description: 'Branch the commit belongs to. This allows you to take advantage of your pipeline and step-level branch filtering rules.'
    default: main
    required: false
  pipelineCommit:
    description: 'Ref, SHA or tag to be built.'
    default: HEAD
    required: false
  pipelineVersion:
    description: 'The pipeline version to be used (e.g. git sha, tag, branch).'
    required: false
    deprecationMessage: "Use pipelineCommit instead."
  triggerMessage:
    description: 'The BK build message to be shown in the UI.'
    default: Triggered automatically with GH actions
    required: false
  artifactName:
    description: Artifact name
    required: false
  artifactPath:
    description: A file, directory or wildcard pattern that describes what to upload
    required: false
  artifactIfNoFilesFound:
    description: |
      Passed to actions/upload-artifact.
      Equivalent to https://github.com/actions/upload-artifact/blob/v3/action.yml#L11
    default: warn
    required: false

outputs:
  build:
    description: "The Buildkite build url"
    value: ${{ steps.trigger-buildkite.outputs.build }}

runs:
  using: "composite"
  steps:
      - uses: hashicorp/vault-action@v2.7.4
        with:
          url: ${{ inputs.vaultUrl }}
          roleId: ${{ inputs.vaultRoleId }}
          secretId: ${{ inputs.vaultSecretId }}
          method: approle
          secrets: |
            ${{ inputs.secret }} token | BUILDKITE_API_ACCESS_TOKEN

      - id: trigger-buildkite
        name: Trigger Buildkite pipeline
        run: |
          ${{ github.action_path }}/run.sh \
            '${{ inputs.org }}' \
            '${{ inputs.pipeline }}' \
            '${{ inputs.buildEnvVars }}' \
            '${{ inputs.waitFor }}' \
            '${{ inputs.printBuildLogs }}' \
            '${{ env.BUILDKITE_API_ACCESS_TOKEN }}' \
            '${{ inputs.triggerMessage }}' \
            '${{ inputs.pipelineVersion || inputs.pipelineCommit }}' \
            '${{ inputs.pipelineBranch }}'
        shell: bash

      - id: download-artifacts
        name: Download artifacts
        if: always() && inputs.waitFor && inputs.artifactName != '' && inputs.artifactPath != ''
        run: |
          pip install globber==0.2.1
          python ${{ github.action_path }}/download_artifacts.py
        env:
          ORG: ${{ inputs.org }}
          PIPELINE: ${{ inputs.pipeline }}
          BUILD_NUMBER: ${{ steps.trigger-buildkite.outputs.build_number }}
          ARTIFACT_PATH: ${{ inputs.artifactPath }}
        shell: bash

      - uses: actions/upload-artifact@v4
        if: always() && steps.download-artifacts.outcome == 'success'
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: ${{ inputs.artifactIfNoFilesFound }}

      - name: Reset environment
        if: always()
        shell: bash
        run: |
          echo "BUILDKITE_API_ACCESS_TOKEN=" >> $GITHUB_ENV

      - name: Cancel Buildkite pipeline
        if: cancelled() && inputs.waitFor && steps.trigger-buildkite.outputs.build_number
        run: |
          ${{ github.action_path }}/cancel.sh \
            '${{ inputs.org }}' \
            '${{ inputs.pipeline }}' \
            '${{ steps.trigger-buildkite.outputs.build_number }}' \
            '${{ env.BUILDKITE_API_ACCESS_TOKEN }}'
        shell: bash
