---
name: 'Elastic Stack Snapshot branches'
description: 'Fetch the current list of active branches with snapshots in Elastic'
inputs:
  exclude-branches:
    description: "Exclude branches comma separated"
    required: false
    type: string
    default: ''
outputs:
  matrix:
    description: "Processed matrix with the required tuples of version and framework"
    value: ${{ steps.generator.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - id: generator
      shell: bash
      run: python ${{ github.action_path }}/script.py
      env:
        EXCLUDE_BRANCHES: ${{ inputs.exclude-branches }}
    - id: debug
      shell: bash
      run: |
        echo 'Matrix: ${{ steps.generator.outputs.matrix }}'
