---
name: 'Elastic Stack Snapshot branches'
description: 'Fetch the current list of active branches with snapshots in Elastic'
outputs:
  matrix:
    description: "Processed matrix with the required tuples of version and framework"
    value: ${{ steps.generator.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - id: generator
      shell: python
      run: |
        import json
        import os
        import requests
        r = requests.get(url='https://storage.googleapis.com/artifacts-api/snapshots/branches.json')
        matrix = {'include': []}
        for branch in r.json()['branches']:
          matrix['include'].append({"branch": branch})
        with open(os.environ.get('GITHUB_OUTPUT'), "a") as f:
          f.write("matrix={}\n".format(json.dumps(matrix)))
    - id: debug
      shell: bash
      run: |
        echo 'Matrix: ${{ steps.generator.outputs.matrix }}'
