# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "elastic/ubuntu-16.04-x86_64"
  config.disksize.size = '50GB'
  config.vm.network "private_network", ip: "192.168.33.12"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "6144"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
  end

  $script = <<-SCRIPT
  if [ ! -e /usr/bin/docker-compose ] ; then
    curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  fi
  if [ ! -e /usr/bin/docker ] ; then
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  fi
  if [ ! -e /usr/bin/hub ] ; then
    curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.2
    cp bin/hub /usr/bin
  fi
  su - vagrant -c 'curl -s https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.9/swarm-client-3.9.jar > swarm-client.jar'
  sudo nohup java -jar swarm-client.jar -labels "linux docker immutable ubuntu" -master http://10.0.2.2:18080 >/tmp/jenkins-swarm.log 2>&1 &
  SCRIPT

  config.vm.provision "shell", inline: $script
end
