name: 'Snapshoty Simple'
description: 'The best way to handle snapshot lifecycle with Vault access.'
inputs:
  config:
    description: 'Path to configuration file'
    default: '.ci/snapshoty.yml'
    required: false
  vaultUrl:
    description: 'Vault URL'
    required: true
  vaultRoleId:
    description: 'Vault role ID'
    required: true
  vaultSecretId:
    description: 'Vault secret ID'
    required: true
runs:
  using: "composite"
  steps:

    - uses: elastic/apm-pipeline-library/.github/actions/docker-login@current
      with:
        registry: docker.elastic.co
        url: ${{ inputs.vaultUrl }}
        roleId: ${{ inputs.vaultRoleId }}
        secretId: ${{ inputs.vaultSecretId }}
        secret: secret/observability-team/ci/docker-registry/prod

    - uses: hashicorp/vault-action@v3
      with:
        url: ${{ inputs.vaultUrl }}
        roleId: ${{ inputs.vaultRoleId }}
        secretId: ${{ inputs.vaultSecretId }}
        method: approle
        secrets: |
          secret/observability-team/ci/snapshoty bucket_name | GCS_BUCKET_NAME ;
          secret/observability-team/ci/snapshoty client_email | GCS_CLIENT_EMAIL ;
          secret/observability-team/ci/snapshoty private_key | GCS_PRIVATE_KEY ;
          secret/observability-team/ci/snapshoty private_key_id | GCS_PRIVATE_KEY_ID ;
          secret/observability-team/ci/snapshoty project_id | GCS_PROJECT

    - uses: elastic/apm-pipeline-library/.github/actions/snapshoty@current
      with:
        config: ${{ inputs.config }}
        bucketName: '${{ env.GCS_BUCKET_NAME }}'
        gcsClientEmail: '${{ env.GCS_CLIENT_EMAIL }}'
        gcsPrivateKey: '${{ env.GCS_PRIVATE_KEY }}'
        gcsPrivateKeyId: '${{ env.GCS_PRIVATE_KEY_ID }}'
        gcsProject: '${{ env.GCS_PROJECT }}'

    - if: ${{ failure() }}
      name: Report snapshoty failure in slack
      uses: elastic/apm-pipeline-library/.github/actions/slack-message@current
      with:
        url: ${{ inputs.vaultUrl }}
        roleId: ${{ inputs.vaultRoleId }}
        secretId: ${{ inputs.vaultSecretId }}
        channel: '#observablt-bots'
        message: "Snapshoty failed, @robots-ci please look what's going on <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>"
