---
name: 'Test Go report'
description: |
  Shows test results in GitHub UI: Gotest (Json)
inputs:
  artifact:
    description: Name or regex of artifact containing test results
    default: 'all'
    required: false
  name:
    description: Name of the check run
    default: 'Go Tests'
    required: false
  path:
    description: |
      Coma separated list of paths to test results
      Supports wildcards via [fast-glob](https://github.com/mrmlnc/fast-glob)
      All matched result files must be of same format
    default: '**/*.json'
    required: true
  list-suites:
    description: |
      Limits which test suites are listed. Supported options:
        - all
        - only-failed
    required: true
    default: 'all'
  list-tests:
    description: |
      Limits which test cases are listed. Supported options:
        - all
        - only-failed
        - none
    required: true
    default: 'all'
  fail-on-error:
    description: Set this action as failed if test report contain any failed test
    required: true
    default: 'true'
  only-summary:
    description: |
      Allows you to generate only the summary.
      If enabled, the report will contain a table listing each test results file and the number of passed,
      failed, and skipped tests.
      Detailed listing of test suites and test cases will be skipped.
    default: 'false'
    required: false
runs:
  using: "composite"
  steps:
    - name: go-json - Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact }}

    - name: go-json - Setup golang
      uses: actions/setup-go@v3
      with:
        go-version: "1.18"

    - name: go-json - Transform go-json to java-junit
      run: |
        go install gotest.tools/gotestsum@latest
        cat ${{ inputs.path }} | gotestsum --junitfile go-json-test-results.xml

    - name: go-json - Report test results
      uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226
      with:
        name: ${{ inputs.name }}
        path: "go-json-test-results.xml"
        reporter: 'java-junit'
        list-suites: ${{ inputs.list-suites }}
        list-tests: ${{ inputs.list-tests }}
        fail-on-error: ${{ inputs.fail-on-error }}
        only-summary: ${{ inputs.only-summary }}
