---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.6b0]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.19.0
    hooks:
      - id: setup-cfg-fmt
        args: [--min-py3-version, "3.6", "--max-py-version", "3.10"]
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "0.5.1"
    hooks:
      - id: tox-ini-fmt
  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        args: ["--ignore=F401,H301,E203,SC200,SC100,W503", "--max-line-length=120"]
        exclude: ^.*/(.venv|.git|__pycache__|.tox|.mypy_cache)
        additional_dependencies: [
          "flake8-bugbear == 21.9.2",
          "flake8-unused-arguments == 0.0.6",
          "flake8-comprehensions == 3.7.0",
          "flake8-spellcheck == 0.24.0",
          "flake8-pytest-style == 1.4.2",
        ]

  - repo: https://github.com/elastic/apm-pipeline-library.git
    rev: current
    hooks:
      - id: check-unicode-non-breaking-spaces
      - id: remove-unicode-non-breaking-spaces
      - id: check-en-dashes
      - id: remove-en-dashes
