name: 'Oblt-cli wrapper'
description: 'Run the oblt-cli wrapper.'
inputs:
  command:
    description: 'The oblt-cli command to run'
    required: true
  token:
    description: 'The GitHub access token.'
    required: true
  slackChannel:
    description: 'The slack channel to notify the status.'
    default: '#observablt-bots'
    required: false
  username:
    description: 'Username to show in the deployments with oblt-cli, format: [a-z0-9]'
    default: 'obltmachine'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          core.warning('This action is deprecated. Use https://github.com/elastic/oblt-actions/tree/main/oblt-cli/run')

    - name: Setup oblt-cli
      uses: elastic/apm-pipeline-library/.github/actions/setup-oblt-cli@current
      with:
        github-token: ${{ inputs.token }}
        slack-channel: ${{ inputs.slackChannel }}
        username: ${{ inputs.username }}
    - name: run oblt-cli
      run: |
        GITHUB_TOKEN=${{ inputs.token }} oblt-cli ${{ inputs.command }} --verbose --disable-banner
      shell: bash
