name: 'Manage GitHub branches'
description: 'Manage the given GitHub branches'
inputs:
  branch:
    description: 'The GitHub branch'
    required: true
  lock:
    description: 'Whether to lock the branch or no'
    required: true
  token:
    description: 'The GitHub access token.'
    required: true
  owner:
    description: 'The GitHub owner'
    default: ${{ github.repository }}
  repo:
    description: 'The GitHub repo'
    default: ${{ github.repository }}
  fail-on-warning:
    description: 'Whether to fail if any warning'
    default: false
runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/lock.py ${{ inputs.owner }} ${{ inputs.repo }} ${{ inputs.branch }} ${{ inputs.lock }} ${{ inputs.fail-on-warning }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
