---
name: OpenTelemetry report
description: Export GitHub actions as OpenTelemetry traces
inputs:
  vaultUrl:
    description: 'Vault URL'
    required: true
  vaultRoleId:
    description: 'Vault role ID'
    required: true
  vaultSecretId:
    description: 'Vault secret ID'
    required: true
  githubToken:
    description: 'GitHub token.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: hashicorp/vault-action@v2.4.2
      with:
        url: ${{ inputs.vaultUrl }}
        roleId: ${{ inputs.vaultRoleId }}
        secretId: ${{ inputs.vaultSecretId }}
        method: approle
        secrets: |
          secret/observability-team/ci/jenkins-logs-robots apmServerOtel | OTLP_ENDPOINT ;
          secret/observability-team/ci/jenkins-logs-robots apmServerToken | OTLP_TOKEN
    - name: Export Workflow Trace
      uses: inception-health/otel-export-trace-action@v1
      with:
        otlpEndpoint: "${{ env.OTLP_ENDPOINT }}"
        otlpHeaders: "Authorization=Bearer ${{ env.OTLP_TOKEN }}"
        otelServiceName: ${{ github.repository }}
        githubToken: ${{ inputs.githubToken }}
        runId: ${{ github.event.workflow_run.id }}
