---
name: OpenTelemetry report
description: Export GitHub actions as OpenTelemetry traces
inputs:
  vaultUrl:
    description: 'Vault URL'
    required: true
  vaultRoleId:
    description: 'Vault role ID'
    required: true
  vaultSecretId:
    description: 'Vault secret ID'
    required: true
  secret:
    description: 'Vault secret with the apmServerOtel and apmServerToken fields.'
    default: secret/observability-team/ci/observability-ci/apm-credentials
    required: false
  githubToken:
    description: 'GitHub token (it uses github.token by default)'
    default: ${{ github.token }}
    required: false
runs:
  using: "composite"
  steps:
    - uses: hashicorp/vault-action@v3.0.0
      with:
        url: ${{ inputs.vaultUrl }}
        roleId: ${{ inputs.vaultRoleId }}
        secretId: ${{ inputs.vaultSecretId }}
        method: approle
        secrets: |
          ${{ inputs.secret }} apmServerOtel | OTLP_ENDPOINT ;
          ${{ inputs.secret }} apmServerToken | OTLP_TOKEN

    - name: Export Workflow Trace
      uses: inception-health/otel-export-trace-action@v1
      with:
        otlpEndpoint: "${{ env.OTLP_ENDPOINT }}"
        otlpHeaders: "Authorization=Bearer ${{ env.OTLP_TOKEN }}"
        otelServiceName: ${{ github.repository }}
        githubToken: ${{ inputs.githubToken }}
        runId: ${{ github.event.workflow_run.id }}
