---
name: 'Get GitHub Personal Access Token'
description: 'Get a temporal GitHub Token using a GitHub App ID and a private key.'
inputs:
  url:
    description: 'Vault URL'
    required: true
  roleId:
    description: 'Vault role ID'
    required: true
  secretId:
    description: 'Vault secret ID'
    required: true
outputs:
  token:
    description: "GitHub token"
    value: ${{ steps.get-token.outputs.token }}
runs:
  using: "composite"
  steps:
    - uses: hashicorp/vault-action@v2.4.2
      with:
        url: ${{ inputs.url }}
        roleId: ${{ inputs.roleId }}
        secretId: ${{ inputs.secretId }}
        method: approle
        secrets: |
          secret/observability-team/ci/github-app app_id | APP_ID ;
          secret/observability-team/ci/github-app installation_id | INSTALLATION_ID ;
          secret/observability-team/ci/github-app key | PRIVATE_KEY
    - name: Get PAT
      id: get-token
      uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06
      with:
        app_id: ${{ env.APP_ID }}
        private_key: ${{ env.PRIVATE_KEY }}
        installation_id: ${{ env.INSTALLATION_ID }}
    - name: Set environment
      run: |
          echo "APP_ID=" >> $GITHUB_ENV
          echo "PRIVATE_KEY=" >> $GITHUB_ENV
          echo "INSTALLATION_ID=" >> $GITHUB_ENV

          echo "GITHUB_TOKEN=${{ needs.get-token.outputs.token }}" >> $GITHUB_ENV
          echo "GIT_USER=apmmachine" >> $GITHUB_ENV
          echo "GIT_EMAIL=apmmachine@users.noreply.github.com" >> $GITHUB_ENV
