---
name: benchmarks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/github-token@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
      - uses: actions/checkout@v3
      - env:
          GH_TOKEN: ${{ env.GITHUB_TOKEN }}
          PROJECT: observability-robots-playground
        run: |-
          gh api -H 'Accept: application/vnd.github.everest-preview+json' \
            repos/elastic/${{ env.PROJECT }}/dispatches \
            -X POST \
            --input - <<< "{\"event_type\":\"benchmark-java\",\"client_payload\":{ \"base\": \"${{ github.event.pull_request.base.sha }}\", \"head\": \"${{ github.event.pull_request.head.sha }}\"}}"
