name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - uses: v1v/otel-upload-test-artifact-action@v2
        if: always()
        continue-on-error: true
        with:
          jobName: "build"
          stepName: "Build with Maven"
          path: "target/surefire-reports/*.xml"
          type: "junit"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
