name: Java CI

on:
  push:
    branches: [main]
  pull_request:

# limit the access of the generated GITHUB_TOKEN
permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@f00bb47e1d89c6d98071d1b69e16a2b63c7fbfc1
        if: always()
        continue-on-error: true
        with:
          files: "target/surefire-reports/*.xml"
      - uses: v1v/otel-upload-test-artifact-action@v2
        if: always()
        continue-on-error: true
        with:
          jobName: "build"
          stepName: "Build with Maven"
          path: "target/surefire-reports/*.xml"
          type: "junit"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
