name: build-test

on:
  push:
    branches: [main]
  pull_request:

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate junit placeholder - to integrate with test-reporter
        run: |-
          cat > python-agent-junit.xml << ENDOFFILE
          <?xml version="1.0" encoding="UTF-8"?>
          <testsuites name="apm-agent-python" tests="1" failures="0" errors="0" time="1">
            <testsuite name="apm-agent-python-docs" errors="0" failures="0" skipped="1" time="1" tests="1">
              <testcase classname="docs" name="Skipped test" time="0">
                <skipped/>
              </testcase>
            </testsuite>
          </testsuites>
          ENDOFFILE
      - if: success() || failure()
        name: Upload JUnit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "python-agent-junit.xml"
