---
name: bump-golang

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 6'

permissions:
  pull-requests: write
  contents: write

env:
  JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: elastic/apm-pipeline-library/.github/actions/updatecli@main
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          pipeline: ./updatecli/updatecli.d/bump-golang.yml
          values: ./updatecli/values.yml
