---
name: generate-elastic-stack-releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * 1-5'

permissions:
  contents: read
  id-token: write

jobs:
  generate-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: elastic/apm-pipeline-library/.github/actions/docker-login@current
        with:
          registry: docker.elastic.co
          secret: secret/observability-team/ci/docker-registry/prod
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - run: .ci/generate-releases.sh
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: elastic/oblt-actions/google/auth@v1

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: releases
          destination: "artifacts-api"
          parent: false
          headers: |-
            content-type: application/json
            x-goog-meta-generator: generate-elastic-stack-releases.yml

      - name: debug
        run: echo "${{ steps.upload-file.outputs.uploaded }}"

      - if: ${{ failure() }}
        uses: elastic/oblt-actions/slack/notify-result@v1
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#observablt-bots"
          message: "<!subteam^S03HM5G8CH0>" # @robots-ci (https://api.slack.com/reference/surfaces/formatting#mentioning-groups)
