---
name: generate-elastic-stack-snapshots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * 1-5'

permissions:
  contents: read
  id-token: write

jobs:
  generate-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: .ci/generate-snapshots.sh

      - uses: elastic/oblt-actions/google/auth@v1

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: snapshots
          glob: "*.json"
          destination: "artifacts-api"
          headers: |-
            content-type: application/json
            x-goog-meta-generator: generate-elastic-stack-snapshots.yml

      - name: debug
        run: echo "${{ steps.upload-file.outputs.uploaded }}"

      - if: ${{ failure() }}
        uses: elastic/oblt-actions/slack/notify-result@v1
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#observablt-bots"
          message: "<!subteam^S03HM5G8CH0>" # @robots-ci (https://api.slack.com/reference/surfaces/formatting#mentioning-groups)
