---
## Get a temporal GitHub Token using a GitHub App ID and a private key.
name: 'Get GitHub Personal Access Token'

on:
  workflow_call:
    outputs:
      pat:
        description: "GitHub token"
        value: ${{ jobs.get-token.outputs.pat }}
jobs:
  get-token:
    runs-on: ubuntu-latest
    outputs:
      pat: ${{ steps.get-token.outputs.pat }}
    steps:
      - uses: hashicorp/vault-action@v2.4.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          method: approle
          secrets: |
            secret/observability-team/ci/github-app app_id | APP_ID
            secret/observability-team/ci/github-app installation_id | INSTALLATION_ID
            secret/observability-team/ci/github-app key | PRIVATE_KEY
      - name: Get PAT
        id: get-token
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06
        with:
          app_id: ${{ env.APP_ID }}
          private_key: ${{ env.PRIVATE_KEY }}
          installation_id: ${{ env.INSTALLATION_ID }}
      - name: Mask PAT
        run: echo "::add-mask::${{ steps.get-token.outputs.pat }}"
        shell: bash
