---
name: lint

on:
  push:
    branches: [main]
  pull_request: ~

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
    - name: Actionlint
      run: |
        go install github.com/rhysd/actionlint/cmd/actionlint@latest
        ls -ltra "$(go env GOPATH)"/bin
        "$(go env GOPATH)"/bin/actionlint -color \
        -format ${{ env.FORMAT }} \
        -ignore 'SC2086:'
      env:
        FORMAT: '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}'
