---
name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows:
      - actions-test
      - build-test
      - job-dsl
      - licenses
      - publish-docker-images
      - pytest_otel-build-test
      - release-drafter
    types: [completed]

jobs:
  otel-export-trace:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/opentelemetry@current
