name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

# Those checks require access to the internal docker registry.
# As we are migrating to GH then we don't need to lint those files.
env:
  SKIP: 'check-jenkins-pipelines,check-jjbb'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/pre-commit@current
