---
name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with: ## let's skip to run for all the files
        extra_args: --help
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Precommit changes
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          pre-commit run --files "${changed_file}"
        done
