---
## get the credentials from the Vault and send an Slack message.
name: 'Send an Slack message'

on:
  workflow_call:
    inputs:
      channel:
        description: 'Slack channel'
        required: true
      message:
        description: 'Slack message on Markdown format'
        required: true
jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/vault-action@v2.4.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          method: approle
          secrets: |
            secret/observability-team/ci/stack-integartion-token integration_token | SLACK_BOT_TOKEN
      - name: Processing message
        uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: '${{ inputs.channel }}'
          payload: |
            {
              "text": "${{ inputs.message }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ inputs.message }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ env.SLACK_BOT_TOKEN }}
