---
name: test-workflow-run

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  dispatch-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get token
        id: get_token
        uses: elastic/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.ELASTIC_OBSERVABILITY_APP_PEM }}
          APP_ID: ${{ secrets.ELASTIC_OBSERVABILITY_APP_ID }}

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - uses: elastic/apm-pipeline-library/.github/actions/workflow-run@feature/github-workflow-run
        with:
          repository: "elastic/observability-robots-playground"
          type: my-event
          token: ${{ steps.get_token.outputs.app_token }}
          payload: '{ "ref": "${{ github.event.pull_request.head.sha }}", "repository": "${{ github.repository }}" }'
