---
name: test-is-admin

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-with-non-elastic-admin:
    runs-on: ubuntu-latest
    steps:

      - uses: elastic/apm-pipeline-library/.github/actions/github-token@main
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - uses: elastic/apm-pipeline-library/.github/actions/is-admin@feature/is-admin
        id: is_admin
        with:
          username: mdelapenya
          token: ${{ env.GITHUB_TOKEN }}

      - name: Assert is no member
        run: test "${{steps.is_admin.outputs.result}}" = "false"

  test-with-elastic-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/github-token@main
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - uses: elastic/apm-pipeline-library/.github/actions/is-admin@feature/is-admin
        id: is_admin
        with:
          username: v1v
          token: ${{ env.GITHUB_TOKEN }}

      - name: Assert is member
        run: test "${{steps.is_admin.outputs.result}}" = "true"
