---
name: test-oblt-cli

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  run-oblt-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        uses: elastic/apm-pipeline-library/.github/actions/setup-git@main

      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@f04aa94d10cf56334d1c580e077ce2e3569e805d
        with:
          private-key: ${{ secrets.ELASTIC_OBSERVABILITY_PRIVATE_KEY }}
          app-id: ${{ secrets.ELASTIC_OBSERVABILITY_APP_ID }}
          repositories: "observability-test-environments"

      - uses: elastic/apm-pipeline-library/.github/actions/oblt-cli@main
        with:
          token: ${{ steps.get_token.outputs.token }}
          command: 'cluster create ccs --remote-cluster=dev-oblt --cluster-name-prefix testgithubaction'
