---
name: test-oblt-cli-create-serverless

on:
  workflow_dispatch: ~
  push:
    branches:
      - main
    paths:
      - '.github/actions/oblt-cli-create-serverless/**'

permissions:
  contents: read

jobs:

  run-oblt-cli-create-serverless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        uses: elastic/apm-pipeline-library/.github/actions/setup-git@main

      - name: Get token
        id: get_token
        uses: elastic/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.ELASTIC_OBSERVABILITY_APP_PEM }}
          APP_ID: ${{ secrets.ELASTIC_OBSERVABILITY_APP_ID }}

      - uses: ./.github/actions/oblt-cli-create-serverless
        with:
          token: ${{ steps.get_token.outputs.app_token }}
          target: 'qa'
          cluster-name-prefix: 'testgithubaction'
          gitops: true
          dry-run: true
