---
name: test-oblt-cli-create-serverless

on:
  workflow_dispatch: ~
  push:
    branches:
      - main
    paths:
      - '.github/actions/oblt-cli-create-serverless/**'

permissions:
  contents: read

jobs:

  run-oblt-cli-create-serverless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        uses: elastic/apm-pipeline-library/.github/actions/setup-git@main

      - uses: elastic/apm-pipeline-library/.github/actions/github-token@main
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - uses: ./.github/actions/oblt-cli-create-serverless
        with:
          token: ${{ env.GITHUB_TOKEN }}
          target: 'qa'
          cluster-name-prefix: 'testgithubaction'
          gitops: true
          dry-run: true
