---
name: test-notify-build-status-integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/actions/notify-build-status/**'
      - '.github/workflows/test-notify-build-status-integration.yml'

jobs:
  test-notify-build-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/notify-build-status
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: '#observablt-bots'
          message: 'Test Github Action Notify Build Status'
      - uses: ./.github/actions/notify-build-status
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: '#observablt-bots'
          message: |
            Test Multiline
            Github Action Notify Build Status
      - uses: ./.github/actions/notify-build-status
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: '#observablt-bots'
