---
name: test-is-member-elastic-org

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-with-non-elastic-user:
    runs-on: ubuntu-latest
    steps:

      - uses: elastic/apm-pipeline-library/.github/actions/is-member-elastic-org@test/use-gh-token-instead
        id: is_elastic_member
        with:
          username: mdelapenya

      - name: Assert is no member
        run: test "${{steps.is_elastic_member.outputs.result}}" = "false"

  test-with-elastic-user:
    runs-on: ubuntu-latest
    steps:

      - uses: elastic/apm-pipeline-library/.github/actions/is-member-elastic-org@test/use-gh-token-instead
        id: is_elastic_member
        with:
          username: apmmachine

      - name: Assert is member
        run: test "${{steps.is_elastic_member.outputs.result}}" = "true"
