---
name: test-comment-reaction

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read

jobs:
  comment-reaction-by-default:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:

      - name: Get token
        id: get_token
        uses: elastic/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.ELASTIC_OBSERVABILITY_APP_PEM }}
          APP_ID: ${{ secrets.ELASTIC_OBSERVABILITY_APP_ID }}

      - uses: elastic/apm-pipeline-library/.github/actions/comment-reaction@main
        with:
          repository: ${{ github.repository }}
          commentId: ${{ github.event.comment.id }}
          emoji: hooray
          token: ${{ steps.get_token.outputs.app_token }}

  comment-reaction-if-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/run-comment-reaction') }}
    steps:

      - name: Get token
        id: get_token
        uses: elastic/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.ELASTIC_OBSERVABILITY_APP_PEM }}
          APP_ID: ${{ secrets.ELASTIC_OBSERVABILITY_APP_ID }}

      - uses: elastic/apm-pipeline-library/.github/actions/comment-reaction@main
        with:
          repository: ${{ github.repository }}
          commentId: ${{ github.event.comment.id }}
          token: ${{ steps.get_token.outputs.app_token }}
