---
name: test-is-member-elastic-org
on:
  pull_request:
    paths:
      - '.github/actions/is-member-elastic-org/**'
  push:
    branches:
      - main
    paths:
      - '.github/actions/is-member-elastic-org/**'

jobs:
  test-with-non-elastic-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: elastic/apm-pipeline-library/.github/actions/github-token@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - uses: ./.github/actions/is-member-elastic-org
        id: is_elastic_member
        with:
          username: victor
          token: ${{ env.GITHUB_TOKEN }}

      - name: Log Result
        run: |
          result=${{steps.is_elastic_member.outputs.result}}
          echo "$result"

  test-with-elastic-user:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: elastic/apm-pipeline-library/.github/actions/github-token@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - uses: ./.github/actions/is-member-elastic-org
        id: is_elastic_member
        with:
          username: v1v
          token: ${{ env.GITHUB_TOKEN }}

      - name: Log Result
        run: |
          result=${{steps.is_elastic_member.outputs.result}}
          echo "$result"
