---
name: test-oblt-cli-cluster-name-validation

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  run-oblt-cli-cluster-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/oblt-cli-cluster-name-validation
        id: validation
        with:
          cluster-name: 'foo'

      - name: Assert is foo
        run: test "${{steps.validation.outputs.cluster-name}}" = "foo"

  run-oblt-cli-cluster-info-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "{\"ClusterName\":\"bar\"}" | tee ${{ github.workspace }}/cluster-info.json

      - uses: ./.github/actions/oblt-cli-cluster-name-validation
        id: validation
        with:
          cluster-info-file: ${{ github.workspace }}/cluster-info.json

      - name: Assert is bar
        run: test "${{steps.validation.outputs.cluster-name}}" = "bar"

  run-oblt-cli-cluster-name-failures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/oblt-cli-cluster-name-validation
        id: validation
        continue-on-error: true
        with:
          cluster-name: ''

      - name: Assert is failure
        run: test "${{steps.validation.outcome}}" = "failure"

      - uses: ./.github/actions/oblt-cli-cluster-name-validation
        id: validation1
        continue-on-error: true
        with:
          cluster-info-file: ''

      - name: Assert is failure
        run: test "${{steps.validation1.outcome}}" = "failure"

      - uses: ./.github/actions/oblt-cli-cluster-name-validation
        id: validation2
        continue-on-error: true
        with:
          cluster-info-file: ''
          cluster-name: ''

      - name: Assert is failure
        run: test "${{steps.validation2.outcome}}" = "failure"

      - run: echo "{\"ClusterName\":\"bar\"}" | tee ${{ github.workspace }}/cluster-info.json

      - uses: ./.github/actions/oblt-cli-cluster-name-validation
        id: validation3
        continue-on-error: true
        with:
          cluster-info-file: ${{ github.workspace }}/cluster-info.json
          cluster-name: 'foo'

      - name: Assert is failure
        run: test "${{steps.validation3.outcome}}" = "failure"
