---
name: test-matrix

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ["main", "current"]
    steps:

      - uses: actions/checkout@v3

      - uses: elastic/apm-pipeline-library/.github/actions/updatecli@feature/support-apply-diff
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          pipeline: ./.ci/bump-test.yml
          command: 'diff'
        env:
          BRANCH: ${{ matrix.branch }}
