---
name: test-oblt-cli-cluster-credentials

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  run-oblt-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        uses: elastic/apm-pipeline-library/.github/actions/setup-git@main

      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@f04aa94d10cf56334d1c580e077ce2e3569e805d
        with:
          private-key: ${{ secrets.ELASTIC_OBSERVABILITY_PRIVATE_KEY }}
          app-id: ${{ secrets.ELASTIC_OBSERVABILITY_APP_ID }}
          repositories: "observability-test-environments"

      - uses: elastic/apm-pipeline-library/.github/actions/oblt-cli-cluster-credentials@main
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          cluster-name: 'dev-oblt'
          vault-url: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}

      - run: curl -X GET "${ELASTICSEARCH_HOST}/_cat/indices?v" -u ${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}
