---
name: test-is-pr-approved

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/actions/is-pr-approved/**'
  push:
    branches: main
    paths:
      - '.github/actions/is-pr-approved/**'

jobs:
  test-is-pr-approved:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/actions/is-pr-approved
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # Must be kept in sync with node version in action.yml 
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Lint, Format, Build, Test & Package
        run: npm run all
      - name: Check nothing changes
        run: npm run check
