---
## Workflow to process the JUnit test results and add a report to the checks.
name: Test Report

on:
  workflow_run:
    workflows: [build-test, job-dsl, pytest_otel-build-test]
    types: [completed]

permissions:
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/test-report@main
        with:
          artifact: test-results             # artifact name
          name: JUnit Tests                  # Name of the check run which will be created
          path: "**/*.xml"                   # Path to test results (inside artifact .zip)
          reporter: java-junit               # Format of test results
