---
#
# Test the kibana-docker-image action if it produces the expected output and if the image can be pulled.
#
name: test-kibana-docker-image-action

on:
  workflow_dispatch: ~
  push:
    branches:
      - main
    paths:
      - ".github/actions/kibana-docker-image/**"
  schedule:
    - cron: '0 6 * * *'

jobs:

  kibana-docker-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        includes:
          - serverless: false
          - serverless: true
    steps:
      - uses: actions/checkout@v4
      - uses: elastic/apm-pipeline-library/.github/actions/docker-login@main
        with:
          registry: docker.elastic.co
          secret: secret/observability-team/ci/docker-registry/prod
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
      - uses: ./.github/actions/kibana-docker-image
        id: kibana-docker-image
        with:
          serverless: ${{ matrix.serverless }}
      - name: Verify
        run: |
          echo "${STACK_VERSION:?}"
          echo "${GIT_COMMIT_SHA:?}"
          echo "${DOCKER_IMAGE_REF:?}"
          docker pull "${DOCKER_IMAGE_REF}"
        env:
          DOCKER_IMAGE_REF: ${{ steps.kibana-docker-image.outputs.kibana-docker-image }}
          GIT_COMMIT_SHA: ${{ steps.kibana-docker-image.outputs.kibana-commit-sha }}
          STACK_VERSION: ${{ steps.kibana-docker-image.outputs.kibana-stack-version }}
      - if: failure()
        uses: elastic/apm-pipeline-library/.github/actions/notify-build-status@main
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: "#observablt-bots"
