---
name: test-docs-preview

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  doc-preview-pr:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/docs-preview@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.repository.name }}
          name: 'observability'
          pr: ${{ github.event.pull_request.id }}

  doc-preview-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/docs-preview@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.repository.name }}
          name: 'observability'
          pr: 513
