---
name: test-notify-build-status-integration

on:
  pull_request_target:
    branches:
      - main
    paths:
      - '.github/actions/notify-build-status/**'
      - '.github/workflows/test-notify-build-status-integration.yml'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/actions/notify-build-status/**'
      - '.github/workflows/test-notify-build-status-integration.yml'

jobs:

  is-pr-approved:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/is-pr-approved@current
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-notify-build-status:
    runs-on: ubuntu-latest
    needs:
      - is-pr-approved
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/notify-build-status
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: '#observablt-bots'
          message: 'Test Github Action Notify Build Status'
      - uses: ./.github/actions/notify-build-status
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: '#observablt-bots'
          message: |
            Test Multiline
            Github Action Notify Build Status
      - uses: ./.github/actions/notify-build-status
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: '#observablt-bots'
