---
name: test-oblt-cli-cluster-credentials

on:
  workflow_dispatch:

jobs:

  run-oblt-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        uses: elastic/apm-pipeline-library/.github/actions/setup-git@main

      - uses: elastic/apm-pipeline-library/.github/actions/github-token@main
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - uses: elastic/apm-pipeline-library/.github/actions/oblt-cli-cluster-credentials@main
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          cluster-name: 'dev-oblt'
          vault-url: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}

      - run: curl -X GET "${ELASTICSEARCH_HOST}/_cat/indices?v" -u ${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}
